apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: local-quay
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-quay
  namespace: local-quay
spec:
  targetNamespaces:
  - local-quay
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: local-quay
spec:
  channel: quay-v3.3
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
